from DB import DB
from JsonParser import JsonParser
import time

startTimeDB = time.time()
DB_Obj = DB()
finishTimeDB = time.time()
print("DB start --- %s seconds ---" % (finishTimeDB - startTimeDB))

startTimeParser = time.time()
Parser_Obj = JsonParser()
finishTimeParser = time.time()
print("Parser start --- %s seconds ---" % (finishTimeParser - startTimeParser))

startTimeP = time.time()
flat_j1 = Parser_Obj.read_json('Json_Examples\Json1.json')
flat_j2 = Parser_Obj.read_json('Json_Examples\Json2.json')
flat_j3 = Parser_Obj.read_json('Json_Examples\Json3.json')
flat_j4 = Parser_Obj.read_json('Json_Examples\Json4.json')
flat_j5 = Parser_Obj.read_json('Json_Examples\Json5.json')
flat_j6 = Parser_Obj.read_json('Json_Examples\Json6.json')
flat_j7 = Parser_Obj.read_json('Json_Examples\Json7.json')
flat_j8 = Parser_Obj.read_json('Json_Examples\Json8.json')
flat_j9 = Parser_Obj.read_json('Json_Examples\Json9.json')
flat_j10 = Parser_Obj.read_json('Json_Examples\Json10.json')
flat_j11 = Parser_Obj.read_json('Json_Examples\Json11.json')
flat_j12 = Parser_Obj.read_json('Json_Examples\Json12.json')
flat_j13 = Parser_Obj.read_json('Json_Examples\Json13.json')
flat_j14 = Parser_Obj.read_json('Json_Examples\Json14.json')
flat_j15 = Parser_Obj.read_json('Json_Examples\Json15.json')
flat_j16 = Parser_Obj.read_json('Json_Examples\Json16.json')
flat_j17 = Parser_Obj.read_json('Json_Examples\Json17.json')
flat_j18 = Parser_Obj.read_json('Json_Examples\Json18.json')
flat_j19 = Parser_Obj.read_json('Json_Examples\Json19.json')
flat_j20 = Parser_Obj.read_json('Json_Examples\Json20.json')
flat_j21 = Parser_Obj.read_json('Json_Examples\Json21.json')
finishTimeP = time.time()
print("Parsing --- %s seconds ---" % (finishTimeP - startTimeP))

startTimeI = time.time()
DB_Obj.insertIntoSensor(flat_j1, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j2, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j3, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j4, 3, "Luis")
DB_Obj.insertIntoSensor(flat_j5, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j6, 4, "Luis")
DB_Obj.insertIntoSensor(flat_j7, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j8, 4, "Luis")
DB_Obj.insertIntoSensor(flat_j9, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j10, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j11, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j12, 10, "Luis")
DB_Obj.insertIntoSensor(flat_j13, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j14, 18, "Luis")
DB_Obj.insertIntoSensor(flat_j15, 21, "Luis")
DB_Obj.insertIntoSensor(flat_j16, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j17, 21, "Luis")
DB_Obj.insertIntoSensor(flat_j18, 12, "Luis")
DB_Obj.insertIntoSensor(flat_j19, 18, "Luis")
DB_Obj.insertIntoSensor(flat_j20, 21, "Luis")
DB_Obj.insertIntoSensor(flat_j21, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j20, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j19, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j18, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j17, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j16, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j15, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j14, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j15, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j14, 3, "Luis")
finishTimeI = time.time()
print("Inserting --- %s seconds ---" % (finishTimeI - startTimeI))

startTime1 = time.time()
queryResult1 = DB_Obj.rangeQueryPerUser('Luis', ['temperature'], {'temperature': '=12'}, '2020-06-02 10:10:10', '2021-08-01 22:36:20.785976')
finishTime1 = time.time()

startTime2 = time.time()
queryResult2 = DB_Obj.queryPerUser('Luis', ['temperature'], {'temperature': '=12'})
finishTime2 = time.time()

startTime3 = time.time()
queryResult3 = DB_Obj.queryPerSensor('Marta', '2', ['sensorid'], {'temperature': '=12'})
finishTime3 = time.time()

startTime5 = time.time()
queryResult5 = DB_Obj.queryPerUser('Luis', ['AVG:temperature'], {'sensorid': '=0001'})
finishTime5 = time.time()

startTime6 = time.time()
queryResult6 = DB_Obj.queryPerUser('Luis', ['MIN:temperature'], {'sensorid': '=0001'})
finishTime6 = time.time()

startTime7 = time.time()
queryResult7 = DB_Obj.queryPerUser('Luis', ['MAX:temperature'], {'sensorid': '=0001'})
finishTime7 = time.time()

startTime8 = time.time()
queryResult8 = DB_Obj.queryPerUser('Luis', ['SUM:temperature'], {'sensorid': '=0001'})
finishTime8 = time.time()

startTime9 = time.time()
queryResult9 = DB_Obj.queryPerUser('Luis', ['CNT:temperature'], {'sensorid': '=0001'})
finishTime9 = time.time()

startTime10 = time.time()
queryResult10 = DB_Obj.queryPerUser('Luis', ['CNT:temperature'], {'sensorid': '=0001', 'timestamp': '>2020-06-02 10:10:10'})
finishTime10 = time.time()

startTime11 = time.time()
queryResult11 = DB_Obj.rangeQueryPerSensor('Marta', '2', ['sensorid'], {'temperature': '>10', 'sensorid': '=0002'}, '2020-06-02 10:10:10', '2021-08-01 22:36:20.785976')
finishTime11 = time.time()

print("\n")
DB_Obj.printResults(queryResult2)
print("Query User --- %s seconds ---" % (finishTime2 - startTime2))
print("\n")
DB_Obj.printResults(queryResult1)
print("Range Query User --- %s seconds ---" % (finishTime1 - startTime1))
print("\n")
DB_Obj.printResults(queryResult3)
print("Query Sensor --- %s seconds ---" % (finishTime3 - startTime3))
print("\n")
DB_Obj.printResults(queryResult11)
print("Range Query Sensor --- %s seconds ---" % (finishTime11 - startTime11))
print("\n")
DB_Obj.printResults(queryResult5)
print("Query Average --- %s seconds ---" % (finishTime5 - startTime5))
print("\n")
DB_Obj.printResults(queryResult6)
print("Query Minimum --- %s seconds ---" % (finishTime6 - startTime6))
print("\n")
DB_Obj.printResults(queryResult7)
print("Query Maximum --- %s seconds ---" % (finishTime7 - startTime7))
print("\n")
DB_Obj.printResults(queryResult8)
print("Query Sum --- %s seconds ---" % (finishTime8 - startTime8))
print("\n")
DB_Obj.printResults(queryResult9)
print("Query Count --- %s seconds ---" % (finishTime9 - startTime9))
print("\n")
DB_Obj.printResults(queryResult10)
print("Query Count2 --- %s seconds ---" % (finishTime10 - startTime10))